version: "3.6"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=WARN"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.forwardedHeaders.insecure"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8321:80"
      - "8322:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: json-file
      options:
        max-size: "10m"
  hass:
    container_name: homeassistant
    image: homeassistant/home-assistant:2021.7
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    expose:
      - 8123
    ports:
      - "8123:8123"
    volumes:
      - ./hass:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.tls.certresolver=myresolver
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    depends_on:
      - sql_db
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "3000:3000"
      - "8091:8091"
    tty: true
    volumes:
      - ./zwavejs:/usr/src/app/store
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
  appdaemon:
    container_name: appdaemon
    restart: unless-stopped
    image: acockburn/appdaemon:4.0.8
    ports:
      - "5050:5050"
    expose:
      - 5050
    volumes:
      - ./appdaemon/config:/conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
    labels:
      - traefik.enable=true
      - traefik.http.routers.appdaemon.rule=(Host(`${DOMAIN}`) && PathPrefix(`/api/appdaemon/`))
      - traefik.http.routers.appdaemon.entrypoints=websecure
      - traefik.http.routers.appdaemon.tls.certresolver=myresolver
      - traefik.http.services.appdaemon.loadbalancer.server.port=5050
    depends_on:
      - hass
  sql_db:
    container_name: sql_db
    image: linuxserver/mariadb # https://hub.docker.com/r/linuxserver/mariadb
    restart: always
    environment:
      - PUID="${UID}"
      - PGID="${GID}"
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - TZ=${TZ}
      - MYSQL_DATABASE=hass
      - MYSQL_USER=hass
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    volumes:
      - ./sql_db/config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
  drbackup:
    container_name: drbackup
    restart: unless-stopped
    build:
      context: ./drbackup
    volumes:
      - ./drbackup:/drbackup
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - sql_db
    entrypoint: "tail -f /dev/null"
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do python3 /drbackup/drbackup.py; sleep 24h & wait $${!}; done;'"
  #esphome:
  #  image: esphome/esphome # https://hub.docker.com/r/esphome/esphome
networks:
  default:
    name: mrhomn
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"