version: "3.6"
services:
  #nginx:
    # /:443 => 8123
    # /api/appdaemon:443 => 5050
  hass:
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "8123:8123"
    volumes:
      - "${PDATA_BASE_PATH}/hass:/config"
    depends_on:
      - sql_db
  #appdaemon:
  #  appdaemon:
  #  container_name: appdaemon
  #  restart: unless-stopped
  #  image: acockburn/appdaemon
  #  environment:
  #    HA_URL: "http://hass:8123"
  #    TOKEN: "${HA_APPDAEMON_KEY}"
  #  ports:
  #    - "5050:5050"
  #  volumes:
  #    - "${PDATA_BASE_PATH}/appdaemon/config:/conf"
  #  depends_on:
  #    - hass
  #  user: "${UID}:${GID}"
  sql_db: 
    image: linuxserver/mariadb # https://hub.docker.com/r/linuxserver/mariadb
    restart: unless-stopped
    environment:
      - PUID="${UID}"
      - PGID="${GID}"
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=${TZ}
      - MYSQL_DATABASE=hass
      - MYSQL_USER=hassdb
      - MYSQL_PASSWORD=changeme
    ports:
      - "3306:3306"
    volumes:
      - "${PDATA_BASE_PATH}/sql_db/config:/config"